language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
    fast_finish: true
    include:
        # Test minimum supported dependencies with the latest and oldest PHP version
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        # Test the latest stable release
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover=build/coverage.xml"

        # Test forcing symfony components version
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 7.4
          env: SYMFONY_VERSION=4.3.*
        - php: 7.4
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=5.0.*
        - php: 7.4
          env: SYMFONY_VERSION=5.0.*

        # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
        # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
